
name: ReadMe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g rdme

      - name: Publish API Definitions
        run: rdme openapi personio-personnel-data-api-oa3.yaml --id=615426c8fee5dc0080ec2fe8 --key "$API_KEY"
